# Generated by Django 4.2 on 2026-03-10 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0009_alter_course_code_alter_course_level_and_more"),
        ("accounts", "0006_remove_user_picture"),
        ("quiz", "0008_alter_quiz_options_alter_mcquestion_choice_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_certification_renewals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_renewals",
                        to="course.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_renewals",
                        to="accounts.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renovación de certificación",
                "verbose_name_plural": "Renovaciones de certificación",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="certificationrenewal",
            index=models.Index(
                fields=["student", "course"], name="quiz_certif_student_b14ac4_idx"
            ),
        ),
    ]
